server:
  port: 8081
spring:
  application:
    name: consul-service-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-interval: 10s

